development: &defaults
  twitter:
    consumer_key: xeUmDpsFOpw5LbyZQrsRHw
    consumer_secret: yOmXDvXDzsWKVXgm9IxvCNpeWNPvXJvMw3awvADxU
    token: 17400516-AHIQND06Qkh9ZIdqTaAjMGORFDBAjMDeKEMPON85v
    token_secret: l3Hk3RkO1kFPQxSMcyeDz4l6Vi6ytIFq7BgqExduI
  rdio:
    consumer_key: 7r5kgbnym8q454pt8t23yw6j
    consumer_secret: 2TmTVNWNDz
  echonest:
    api_key: 4T42EAJNJSEO6NPVA 
    consumer_key: 4d0a1aef73524ebbb063bba314c2a32e
    consumer_secret: 4DL6qbmIQcqXgZ3wnPBmkw

test:
  <<: *defaults

production:
  <<: *defaults