development: &defaults
  twitter:
    consumer_key: xeUmDpsFOpw5LbyZQrsRHw
    consumer_secret: yOmXDvXDzsWKVXgm9IxvCNpeWNPvXJvMw3awvADxU
  rdio:
    consumer_key: 7r5kgbnym8q454pt8t23yw6j
    consumer_secret: 2TmTVNWNDz

test:
  <<: *defaults

production:
  <<: *defaults